# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ForcePlateProcessing.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
import matplotlib.pyplot as plt
from matplotlib.backends.backend_qt4agg import FigureCanvasQTAgg as FigureCanvas
from matplotlib.backends.backend_qt4agg import NavigationToolbar2QT as NavigationToolbar
from HelpWindow import Ui_Dialog

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1292, 622)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 0, 1271, 571))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout = QtGui.QGridLayout(self.tab)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.forcePlateImage = QtGui.QLabel(self.tab)
        self.forcePlateImage.setObjectName(_fromUtf8("forcePlateImage"))
        self.forcePlateImage.setPixmap(QtGui.QPixmap('Plates.png'))
        self.gridLayout.addWidget(self.forcePlateImage, 1, 1, 3, 3, QtCore.Qt.AlignCenter)
        self.groupBoxParameters = QtGui.QGroupBox(self.tab)
        self.groupBoxParameters.setObjectName(_fromUtf8("groupBoxParameters"))
        self.formLayout = QtGui.QFormLayout(self.groupBoxParameters)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.labelSampling = QtGui.QLabel(self.groupBoxParameters)
        self.labelSampling.setObjectName(_fromUtf8("labelSampling"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.labelSampling)
        self.lineSampling = QtGui.QLineEdit(self.groupBoxParameters)
        self.lineSampling.setObjectName(_fromUtf8("lineSampling"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineSampling)
        self.labelVMax = QtGui.QLabel(self.groupBoxParameters)
        self.labelVMax.setObjectName(_fromUtf8("labelVMax"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.labelVMax)
        self.lineVMax = QtGui.QLineEdit(self.groupBoxParameters)
        self.lineVMax.setAutoFillBackground(False)
        self.lineVMax.setReadOnly(True)
        self.lineVMax.setObjectName(_fromUtf8("lineVMax"))
        self.lineVMax.setStyleSheet("QLineEdit { background-color : rgb(211, 211, 211); }")
        font = self.lineVMax.font()      
        font.setPointSize(10)               
        self.lineVMax.setFont(font)  
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineVMax)
        self.labelGain = QtGui.QLabel(self.groupBoxParameters)
        self.labelGain.setObjectName(_fromUtf8("labelGain"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.labelGain)
        self.lineGain = QtGui.QLineEdit(self.groupBoxParameters)
        self.lineGain.setReadOnly(True)
        self.lineGain.setObjectName(_fromUtf8("lineGain"))
        self.lineGain.setStyleSheet("QLineEdit { background-color : rgb(211, 211, 211); }")
        font = self.lineGain.font()      
        font.setPointSize(10)               
        self.lineGain.setFont(font) 
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineGain)
        self.labelMult = QtGui.QLabel(self.groupBoxParameters)
        self.labelMult.setObjectName(_fromUtf8("labelMult"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.labelMult)
        self.lineMult = QtGui.QLineEdit(self.groupBoxParameters)
        self.lineMult.setReadOnly(True)
        self.lineMult.setObjectName(_fromUtf8("lineMult"))
        self.lineMult.setStyleSheet("QLineEdit { background-color : rgb(211, 211, 211); }")
        font = self.lineMult.font()      
        font.setPointSize(10)               
        self.lineMult.setFont(font) 
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.lineMult)
        self.labelX = QtGui.QLabel(self.groupBoxParameters)
        self.labelX.setObjectName(_fromUtf8("labelX"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.labelX)
        self.lineX = QtGui.QLineEdit(self.groupBoxParameters)
        self.lineX.setReadOnly(True)
        self.lineX.setObjectName(_fromUtf8("lineX"))
        self.lineX.setStyleSheet("QLineEdit { background-color : rgb(211, 211, 211); }")
        font = self.lineX.font()      
        font.setPointSize(10)               
        self.lineX.setFont(font) 
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.lineX)
        self.labelY = QtGui.QLabel(self.groupBoxParameters)
        self.labelY.setObjectName(_fromUtf8("labelY"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.labelY)
        self.lineY = QtGui.QLineEdit(self.groupBoxParameters)
        self.lineY.setReadOnly(True)
        self.lineY.setObjectName(_fromUtf8("lineY"))
        self.lineY.setStyleSheet("QLineEdit { background-color : rgb(211, 211, 211); }")
        font = self.lineY.font()      
        font.setPointSize(10)               
        self.lineY.setFont(font) 
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.lineY)
        self.labelZ = QtGui.QLabel(self.groupBoxParameters)
        self.labelZ.setObjectName(_fromUtf8("labelZ"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.labelZ)
        self.lineZ = QtGui.QLineEdit(self.groupBoxParameters)
        self.lineZ.setReadOnly(True)
        self.lineZ.setObjectName(_fromUtf8("lineZ"))
        self.lineZ.setStyleSheet("QLineEdit { background-color : rgb(211, 211, 211); }")
        font = self.lineZ.font()      
        font.setPointSize(10)               
        self.lineZ.setFont(font) 
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.lineZ)
        self.gridLayout.addWidget(self.groupBoxParameters, 3, 0, 2, 1)
        self.labelDirectory = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelDirectory.setFont(font)
        self.labelDirectory.setObjectName(_fromUtf8("labelDirectory"))
        self.gridLayout.addWidget(self.labelDirectory, 0, 0, 1, 1)
        self.comboBoxFP = QtGui.QComboBox(self.tab)
        self.comboBoxFP.setObjectName(_fromUtf8("comboBoxFP"))
        self.comboBoxFP.addItem(_fromUtf8(""))
        self.comboBoxFP.addItem(_fromUtf8(""))
        self.comboBoxFP.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboBoxFP, 2, 0, 1, 1)
        self.listDirectory = QtGui.QListWidget(self.tab)
        self.listDirectory.setObjectName(_fromUtf8("listDirectory"))
        self.gridLayout.addWidget(self.listDirectory, 1, 0, 1, 1)
        self.progressTrial = QtGui.QProgressBar(self.tab)
        self.progressTrial.setProperty("value", 0)
        self.progressTrial.setObjectName(_fromUtf8("progressTrial"))
        self.gridLayout.addWidget(self.progressTrial, 4, 1, 1, 1)
        self.lineTrialName = QtGui.QLineEdit(self.tab)
        self.lineTrialName.setObjectName(_fromUtf8("lineTrialName"))
        self.gridLayout.addWidget(self.lineTrialName, 4, 2, 1, 1)
        self.pushProcess = QtGui.QPushButton(self.tab)
        self.pushProcess.setObjectName(_fromUtf8("pushProcess"))
        self.gridLayout.addWidget(self.pushProcess, 4, 3, 1, 1)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))

        # Define second tab
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.formLayoutResults = QtGui.QFormLayout(self.tab_2)
        self.formLayoutResults.setObjectName(_fromUtf8("formLayoutResults"))
        self.groupBoxResults = QtGui.QGroupBox(self.tab_2)
        self.groupBoxResults.setObjectName(_fromUtf8("groupBoxResults"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBoxResults)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.lineMinCOPx = QtGui.QLineEdit(self.groupBoxResults)
        self.lineMinCOPx.setReadOnly(True)
        self.lineMinCOPx.setObjectName(_fromUtf8("lineMinCOPx"))
        self.lineMinCOPx.setStyleSheet("QLineEdit { background-color : rgb(211, 211, 211); }")
        font = self.lineMinCOPx.font()      
        font.setPointSize(10)               
        self.lineMinCOPx.setFont(font) 
        self.gridLayout_2.addWidget(self.lineMinCOPx, 5, 3, 1, 1)
        self.lineMinCOPy = QtGui.QLineEdit(self.groupBoxResults)
        self.lineMinCOPy.setReadOnly(True)
        self.lineMinCOPy.setObjectName(_fromUtf8("lineMinCOPy"))
        self.lineMinCOPy.setStyleSheet("QLineEdit { background-color : rgb(211, 211, 211); }")
        font = self.lineMinCOPy.font()      
        font.setPointSize(10)               
        self.lineMinCOPy.setFont(font) 
        self.gridLayout_2.addWidget(self.lineMinCOPy, 5, 4, 1, 1)
        self.lineSDCOPx = QtGui.QLineEdit(self.groupBoxResults)
        self.lineSDCOPx.setReadOnly(True)
        self.lineSDCOPx.setObjectName(_fromUtf8("lineSDCOPx"))
        self.lineSDCOPx.setStyleSheet("QLineEdit { background-color : rgb(211, 211, 211); }")
        font = self.lineSDCOPx.font()      
        font.setPointSize(10)               
        self.lineSDCOPx.setFont(font) 
        self.gridLayout_2.addWidget(self.lineSDCOPx, 3, 3, 1, 1)
        self.lineCOVCOPx = QtGui.QLineEdit(self.groupBoxResults)
        self.lineCOVCOPx.setReadOnly(True)
        self.lineCOVCOPx.setObjectName(_fromUtf8("lineCOVCOPx"))
        self.lineCOVCOPx.setStyleSheet("QLineEdit { background-color : rgb(211, 211, 211); }")
        font = self.lineCOVCOPx.font()      
        font.setPointSize(10)               
        self.lineCOVCOPx.setFont(font) 
        self.gridLayout_2.addWidget(self.lineCOVCOPx, 4, 3, 1, 1)
        self.lineSDCOPy = QtGui.QLineEdit(self.groupBoxResults)
        self.lineSDCOPy.setReadOnly(True)
        self.lineSDCOPy.setObjectName(_fromUtf8("lineSDCOPy"))
        self.lineSDCOPy.setStyleSheet("QLineEdit { background-color : rgb(211, 211, 211); }")
        font = self.lineSDCOPy.font()      
        font.setPointSize(10)               
        self.lineSDCOPy.setFont(font) 
        self.gridLayout_2.addWidget(self.lineSDCOPy, 3, 4, 1, 1)
        self.lineMeanCOPy = QtGui.QLineEdit(self.groupBoxResults)
        self.lineMeanCOPy.setReadOnly(True)
        self.lineMeanCOPy.setObjectName(_fromUtf8("lineMeanCOPy"))
        self.lineMeanCOPy.setStyleSheet("QLineEdit { background-color : rgb(211, 211, 211); }")
        font = self.lineMeanCOPy.font()      
        font.setPointSize(10)               
        self.lineMeanCOPy.setFont(font) 
        self.gridLayout_2.addWidget(self.lineMeanCOPy, 2, 4, 1, 1)
        self.labelMeanCOP = QtGui.QLabel(self.groupBoxResults)
        self.labelMeanCOP.setObjectName(_fromUtf8("labelMeanCOP"))
        self.gridLayout_2.addWidget(self.labelMeanCOP, 2, 0, 1, 1)
        self.labelMeanSD = QtGui.QLabel(self.groupBoxResults)
        self.labelMeanSD.setObjectName(_fromUtf8("labelMeanSD"))
        self.gridLayout_2.addWidget(self.labelMeanSD, 3, 0, 1, 1)
        self.labelMeanCOV = QtGui.QLabel(self.groupBoxResults)
        self.labelMeanCOV.setObjectName(_fromUtf8("labelMeanCOV"))
        self.gridLayout_2.addWidget(self.labelMeanCOV, 4, 0, 1, 1)
        self.lineCOVCOPy = QtGui.QLineEdit(self.groupBoxResults)
        self.lineCOVCOPy.setReadOnly(True)
        self.lineCOVCOPy.setObjectName(_fromUtf8("lineCOVCOPy"))
        self.lineCOVCOPy.setStyleSheet("QLineEdit { background-color : rgb(211, 211, 211); }")
        font = self.lineCOVCOPy.font()      
        font.setPointSize(10)               
        self.lineCOVCOPy.setFont(font) 
        self.gridLayout_2.addWidget(self.lineCOVCOPy, 4, 4, 1, 1)
        self.labelMeanMin = QtGui.QLabel(self.groupBoxResults)
        self.labelMeanMin.setObjectName(_fromUtf8("labelMeanMin"))
        self.gridLayout_2.addWidget(self.labelMeanMin, 5, 0, 1, 2)
        self.labelMeanMax = QtGui.QLabel(self.groupBoxResults)
        self.labelMeanMax.setObjectName(_fromUtf8("labelMeanMax"))
        self.gridLayout_2.addWidget(self.labelMeanMax, 6, 0, 1, 2)
        self.lineMeanCOPx = QtGui.QLineEdit(self.groupBoxResults)
        self.lineMeanCOPx.setReadOnly(True)
        self.lineMeanCOPx.setObjectName(_fromUtf8("lineMeanCOPx"))
        self.lineMeanCOPx.setStyleSheet("QLineEdit { background-color : rgb(211, 211, 211); }")
        font = self.lineMeanCOPx.font()      
        font.setPointSize(10)               
        self.lineMeanCOPx.setFont(font) 
        self.gridLayout_2.addWidget(self.lineMeanCOPx, 2, 3, 1, 1)
        self.lineMaxCOPx = QtGui.QLineEdit(self.groupBoxResults)
        self.lineMaxCOPx.setReadOnly(True)
        self.lineMaxCOPx.setObjectName(_fromUtf8("lineMaxCOPx"))
        self.lineMaxCOPx.setStyleSheet("QLineEdit { background-color : rgb(211, 211, 211); }")
        font = self.lineMaxCOPx.font()      
        font.setPointSize(10)               
        self.lineMaxCOPx.setFont(font) 
        self.gridLayout_2.addWidget(self.lineMaxCOPx, 6, 3, 1, 1)
        self.lineMaxCOPy = QtGui.QLineEdit(self.groupBoxResults)
        self.lineMaxCOPy.setReadOnly(True)
        self.lineMaxCOPy.setObjectName(_fromUtf8("lineMaxCOPy"))
        self.lineMaxCOPy.setStyleSheet("QLineEdit { background-color : rgb(211, 211, 211); }")
        font = self.lineMaxCOPy.font()      
        font.setPointSize(10)               
        self.lineMaxCOPy.setFont(font) 
        self.gridLayout_2.addWidget(self.lineMaxCOPy, 6, 4, 1, 1)
        self.labelCOPx = QtGui.QLabel(self.groupBoxResults)
        self.labelCOPx.setObjectName(_fromUtf8("labelCOPx"))
        self.gridLayout_2.addWidget(self.labelCOPx, 1, 3, 1, 1)
        self.labelCOPy = QtGui.QLabel(self.groupBoxResults)
        self.labelCOPy.setObjectName(_fromUtf8("labelCOPy"))
        self.gridLayout_2.addWidget(self.labelCOPy, 1, 4, 1, 1)
        self.formLayoutResults.setWidget(2, QtGui.QFormLayout.FieldRole, self.groupBoxResults)
        self.groupBoxSave = QtGui.QGroupBox(self.tab_2)
        self.groupBoxSave.setObjectName(_fromUtf8("groupBoxSave"))
        self.formLayout_2 = QtGui.QFormLayout(self.groupBoxSave)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.checkBoxCOPPos = QtGui.QCheckBox(self.groupBoxResults)
        self.checkBoxCOPPos.setObjectName(_fromUtf8("checkBoxCOPPos"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.checkBoxCOPPos)
        self.checkBoxCOPVel = QtGui.QCheckBox(self.groupBoxResults)
        self.checkBoxCOPVel.setObjectName(_fromUtf8("checkBoxCOPVel"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.checkBoxCOPVel)
        self.checkBoxMSE = QtGui.QCheckBox(self.groupBoxResults)
        self.checkBoxMSE.setObjectName(_fromUtf8("checkBoxMSE"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.checkBoxMSE)
        self.pushSave = QtGui.QPushButton(self.groupBoxResults)
        self.pushSave.setObjectName(_fromUtf8("pushSave"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.SpanningRole, self.pushSave)
        self.formLayoutResults.setWidget(2, QtGui.QFormLayout.LabelRole, self.groupBoxSave)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        MainWindow.setCentralWidget(self.centralwidget)
        self.figure = plt.figure()    
        self.canvas = FigureCanvas(self.figure)     
        self.toolbar = NavigationToolbar(self.canvas, self)
        self.formLayoutResults.setWidget(0, QtGui.QFormLayout.SpanningRole, self.canvas)
        self.formLayoutResults.setWidget(1, QtGui.QFormLayout.SpanningRole, self.toolbar)

        # Menu bar characterization
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1292, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen_Directory = QtGui.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.actionOpen_Directory.setFont(font)
        self.actionOpen_Directory.setObjectName(_fromUtf8("actionOpen_Directory"))
        self.actionOpen_Trial = QtGui.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.actionOpen_Trial.setFont(font)
        self.actionOpen_Trial.setObjectName(_fromUtf8("actionOpen_Trial"))
        self.actionQuit_Application = QtGui.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.actionQuit_Application.setFont(font)
        self.actionQuit_Application.setObjectName(_fromUtf8("actionQuit_Application"))
        self.actionAbout = QtGui.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.actionAbout.setFont(font)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        #self.actionBack_to_Program = QtGui.QAction(MainWindow)
        #self.actionBack_to_Program.setObjectName(_fromUtf8("actionBack_to_Program"))
        self.menuFile.addAction(self.actionOpen_Directory)
        self.menuFile.addAction(self.actionOpen_Trial)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit_Application)
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addSeparator()
        #self.menuHelp.addAction(self.actionBack_to_Program)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Centre of Pressure Program", None))
        MainWindow.setWindowIcon(QtGui.QIcon('python-icon_1_orig.png'))
        self.groupBoxParameters.setTitle(_translate("MainWindow", "Force Plate Parameters", None))
        self.labelSampling.setText(_translate("MainWindow", "Sampling Rate", None))
        self.lineSampling.setText(_translate("MainWindow", "1000", None))
        self.labelVMax.setText(_translate("MainWindow", "Voltage Maximum", None))
        self.lineVMax.setText(_translate("MainWindow", "10", None))
        self.labelGain.setText(_translate("MainWindow", "Gain", None))
        self.lineGain.setText(_translate("MainWindow", "4000", None))
        self.labelMult.setText(_translate("MainWindow", "Multiplier", None))
        self.lineMult.setText(_translate("MainWindow", "0.000001", None))
        self.labelX.setText(_translate("MainWindow", "Force Plate Origin (x)", None))
        self.labelY.setText(_translate("MainWindow", "Force Plate Origin (y)", None))
        self.labelZ.setText(_translate("MainWindow", "Force Plate Origin (z)", None))
        self.labelDirectory.setText(_translate("MainWindow", "Directory List", None))
        self.comboBoxFP.setItemText(0, _translate("MainWindow", "Choose Force Plate", None))
        self.comboBoxFP.setItemText(1, _translate("MainWindow", "Force Plate #1", None))
        self.comboBoxFP.setItemText(2, _translate("MainWindow", "Force Plate #2", None))
        self.pushProcess.setText(_translate("MainWindow", "Process Trial", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Set-up Processing Parameters", None))
        self.groupBoxResults.setTitle(_translate("MainWindow", "Results", None))
        self.labelMeanCOP.setText(_translate("MainWindow", "Mean", None))
        self.labelMeanSD.setText(_translate("MainWindow", "SD", None))
        self.labelMeanCOV.setText(_translate("MainWindow", "COV", None))
        self.labelMeanMin.setText(_translate("MainWindow", "Minimum", None))
        self.labelMeanMax.setText(_translate("MainWindow", "Maximum", None))
        self.labelCOPx.setText(_translate("MainWindow", "CoPx", None))
        self.labelCOPy.setText(_translate("MainWindow", "CoPy", None))
        self.groupBoxSave.setTitle(_translate("MainWindow", "Save", None))
        self.checkBoxCOPPos.setText(_translate("MainWindow", "CoP Position (m)", None))
        self.checkBoxCOPVel.setText(_translate("MainWindow", "CoP Velocity (m/s)", None))
        self.checkBoxMSE.setText(_translate("MainWindow", "Multi-Scale Entropy", None))
        self.pushSave.setText(_translate("MainWindow", "Save Results", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Results", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.actionOpen_Directory.setText(_translate("MainWindow", "Open Directory", None))
        self.actionOpen_Trial.setText(_translate("MainWindow", "Open Trial", None))
        self.actionQuit_Application.setText(_translate("MainWindow", "Quit Application", None))
        self.actionAbout.setText(_translate("MainWindow", "About", None))
        #self.actionBack_to_Program.setText(_translate("MainWindow", "Back to Program", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

